//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFILIADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AFILIADOS()
        {
            this.DATOS_BANCARIOS_AFILIADOS = new HashSet<DATOS_BANCARIOS_AFILIADOS>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int ID_AFILIADO { get; set; }
        public int ID_USUARIO_PER { get; set; }
        public string COD_AFILIADO { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<int> VENTAS_TOTALES { get; set; }
        public Nullable<double> VALOR_COBRAR { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATOS_BANCARIOS_AFILIADOS> DATOS_BANCARIOS_AFILIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
