//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRITO_COMPRAS
    {
        public int ID_CARRITO { get; set; }
        public int ID_USUARIO { get; set; }
        public int CANTIDAD { get; set; }
        public int ID_TALLA_PRO { get; set; }
        public int ID_COLOR_PRO { get; set; }
        public double PRECIO_PRO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public System.DateTime FECHA_CRE { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual COLORES_PRODUCTO COLORES_PRODUCTO { get; set; }
        public virtual TALLAS_PRODUCTO TALLAS_PRODUCTO { get; set; }
    }
}
