//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COD_DESCUENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COD_DESCUENTO()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int ID_DESCUENTO { get; set; }
        public string COD_DES { get; set; }
        public int DESCUENTO { get; set; }
        public int CANT_PER_USO { get; set; }
        public Nullable<int> ID_SUBCATEGORIA { get; set; }
    
        public virtual SUBCATEGORIAS SUBCATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
