//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONJUNTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONJUNTO()
        {
            this.DETALLE_CONJUNTO = new HashSet<DETALLE_CONJUNTO>();
        }
    
        public int ID_CONJUNTO { get; set; }
        public string NOM_CONJUNTO { get; set; }
        public double PRECIO_TOTAL { get; set; }
        public double PRECIO_PORMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONJUNTO> DETALLE_CONJUNTO { get; set; }
    }
}
