//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_BANCARIOS_AFILIADOS
    {
        public int ID_DATOS_BANCARIOS { get; set; }
        public int ID_AFILIADO_PER { get; set; }
        public string NOMBRE_BANCO { get; set; }
        public string TIPO_DE_CUENTA { get; set; }
        public string NOMBRE_CUENTA { get; set; }
        public string NUM_CUENTA { get; set; }
    
        public virtual AFILIADOS AFILIADOS { get; set; }
    }
}
