//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_REGALO
    {
        public int ID_DET_REGALO { get; set; }
        public Nullable<int> ID_VENTA_PER { get; set; }
        public string DESTINATARIO { get; set; }
        public Nullable<int> ID_TIPO_ENVOLTURA { get; set; }
        public string MENSAJE { get; set; }
        public string EXTRA { get; set; }
    
        public virtual TIPO_EMVOLTURA TIPO_EMVOLTURA { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
