//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_VENTA()
        {
            this.DETALLE_PERSONALIZADO = new HashSet<DETALLE_PERSONALIZADO>();
        }
    
        public int ID_DETALLE_VENTA { get; set; }
        public int ID_VENTA_PER { get; set; }
        public int ID_PRODUCTO_PER { get; set; }
        public int ID_COLOR_PRO { get; set; }
        public int ID_TALLA_PRO { get; set; }
        public int CANTIDAD { get; set; }
        public int ESTADO { get; set; }
        public Nullable<int> PERSONALIZABLE { get; set; }
    
        public virtual COLORES_PRODUCTO COLORES_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PERSONALIZADO> DETALLE_PERSONALIZADO { get; set; }
        public virtual TALLAS_PRODUCTO TALLAS_PRODUCTO { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
