//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PERSONALIZADO
    {
        public int ID_DETALL_PER { get; set; }
        public int ID_DETALLE_PER { get; set; }
        public string IMAGEN { get; set; }
        public string DETALLES { get; set; }
    
        public virtual DETALLE_VENTA DETALLE_VENTA { get; set; }
    }
}
