//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CONJUNTO
    {
        public int ID_DET_CONJ { get; set; }
        public Nullable<int> ID_CONJ_PER { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
    
        public virtual CONJUNTO CONJUNTO { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
