//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECCIONES()
        {
            this.USUARIOS1 = new HashSet<USUARIOS>();
        }
    
        public int ID_DIREC { get; set; }
        public int ID_USU_PER { get; set; }
        public Nullable<int> ID_CIUDAD { get; set; }
        public string NOM_REC { get; set; }
        public string CEDULA { get; set; }
        public string TELEFONO { get; set; }
        public string CALLE_PRINPICAL { get; set; }
        public string CALLE_SECUNDARIA { get; set; }
        public string NUMERO_CASA { get; set; }
        public string REFERECNIA { get; set; }
        public string CODIGO_POS { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public int ESTADO { get; set; }
        public Nullable<double> LONGITUD { get; set; }
        public Nullable<double> LATITUD { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS1 { get; set; }
    }
}
