//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_DESEOS
    {
        public int ID_DESEO { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public System.DateTime FECHA_CREA { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
