//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorahApiEntities : DbContext
    {
        public NorahApiEntities()
            : base("name=NorahApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AFILIADOS> AFILIADOS { get; set; }
        public virtual DbSet<CARRITO_COMPRAS> CARRITO_COMPRAS { get; set; }
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<CIUDADES> CIUDADES { get; set; }
        public virtual DbSet<COD_DESCUENTO> COD_DESCUENTO { get; set; }
        public virtual DbSet<COLECCIONES> COLECCIONES { get; set; }
        public virtual DbSet<COLORES> COLORES { get; set; }
        public virtual DbSet<COLORES_PRODUCTO> COLORES_PRODUCTO { get; set; }
        public virtual DbSet<CONJUNTO> CONJUNTO { get; set; }
        public virtual DbSet<DATOS_BANCARIOS_AFILIADOS> DATOS_BANCARIOS_AFILIADOS { get; set; }
        public virtual DbSet<DETALLE_COLECCION> DETALLE_COLECCION { get; set; }
        public virtual DbSet<DETALLE_CONJUNTO> DETALLE_CONJUNTO { get; set; }
        public virtual DbSet<DETALLE_PERSONALIZADO> DETALLE_PERSONALIZADO { get; set; }
        public virtual DbSet<DETALLE_REGALO> DETALLE_REGALO { get; set; }
        public virtual DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual DbSet<DETALLES_PRODUCTO> DETALLES_PRODUCTO { get; set; }
        public virtual DbSet<DIRECCIONES> DIRECCIONES { get; set; }
        public virtual DbSet<ESTADOS_ENVIOS> ESTADOS_ENVIOS { get; set; }
        public virtual DbSet<ESTADOS_VENTA> ESTADOS_VENTA { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<IMAGENES_PRODUCTO> IMAGENES_PRODUCTO { get; set; }
        public virtual DbSet<IMAGENES_RESENA> IMAGENES_RESENA { get; set; }
        public virtual DbSet<LISTA_DESEOS> LISTA_DESEOS { get; set; }
        public virtual DbSet<METODOS_PAGO> METODOS_PAGO { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<RESENAS> RESENAS { get; set; }
        public virtual DbSet<SUBCATEGORIAS> SUBCATEGORIAS { get; set; }
        public virtual DbSet<TALLAS> TALLAS { get; set; }
        public virtual DbSet<TALLAS_PRODUCTO> TALLAS_PRODUCTO { get; set; }
        public virtual DbSet<TIPO_EMVOLTURA> TIPO_EMVOLTURA { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<PORTADA> PORTADA { get; set; }
        public virtual DbSet<SECCIONES> SECCIONES { get; set; }
        public virtual DbSet<TAGS> TAGS { get; set; }
        public virtual DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
    }
}
