//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.CARRITO_COMPRAS = new HashSet<CARRITO_COMPRAS>();
            this.COLORES_PRODUCTO = new HashSet<COLORES_PRODUCTO>();
            this.DETALLE_COLECCION = new HashSet<DETALLE_COLECCION>();
            this.DETALLE_CONJUNTO = new HashSet<DETALLE_CONJUNTO>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
            this.DETALLES_PRODUCTO = new HashSet<DETALLES_PRODUCTO>();
            this.IMAGENES_PRODUCTO = new HashSet<IMAGENES_PRODUCTO>();
            this.LISTA_DESEOS = new HashSet<LISTA_DESEOS>();
            this.TAGS = new HashSet<TAGS>();
            this.RESENAS = new HashSet<RESENAS>();
            this.TALLAS_PRODUCTO = new HashSet<TALLAS_PRODUCTO>();
        }
    
        public int ID_PRO { get; set; }
        public int ID_TIPO { get; set; }
        public string MARCA { get; set; }
        public string NOM_PRO { get; set; }
        public string SUBTITULO_PRO { get; set; }
        public int ID_GENERO { get; set; }
        public double PRECIO_PRO { get; set; }
        public double PRE_DESCU_PRO { get; set; }
        public double COSTO_ENVIO { get; set; }
        public int DIAS_TARDA_LLEGAR { get; set; }
        public int STOCK { get; set; }
        public string DESCRIPCION_PRO { get; set; }
        public double CALIFICACION_PRO { get; set; }
        public int ID_SUBCATEGORIA_PER { get; set; }
        public int CANTIDAD_VENDIDA { get; set; }
        public int ESTADO { get; set; }
        public int PERSONALIZABLE { get; set; }
        public string DESCRIP_PERSONALIZABLE { get; set; }
        public int ID_SECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO_COMPRAS> CARRITO_COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLORES_PRODUCTO> COLORES_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COLECCION> DETALLE_COLECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONJUNTO> DETALLE_CONJUNTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_PRODUCTO> DETALLES_PRODUCTO { get; set; }
        public virtual GENERO GENERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGENES_PRODUCTO> IMAGENES_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_DESEOS> LISTA_DESEOS { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAGS> TAGS { get; set; }
        public virtual SECCIONES SECCIONES { get; set; }
        public virtual SUBCATEGORIAS SUBCATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESENAS> RESENAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TALLAS_PRODUCTO> TALLAS_PRODUCTO { get; set; }
    }
}
