//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGS
    {
        public int ID_TAG { get; set; }
        public int ID_PRO_PER { get; set; }
        public string TAG { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
