//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALLAS_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TALLAS_PRODUCTO()
        {
            this.CARRITO_COMPRAS = new HashSet<CARRITO_COMPRAS>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public int ID_TALL_PRO { get; set; }
        public int ID_PRO_PER { get; set; }
        public int ID_TALLA_PER { get; set; }
        public Nullable<double> PRECIO_TALL { get; set; }
        public Nullable<double> PRECIO_TALL_PROM { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO_COMPRAS> CARRITO_COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual TALLAS TALLAS { get; set; }
    }
}
