//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.AFILIADOS = new HashSet<AFILIADOS>();
            this.CARRITO_COMPRAS = new HashSet<CARRITO_COMPRAS>();
            this.DIRECCIONES = new HashSet<DIRECCIONES>();
            this.LISTA_DESEOS = new HashSet<LISTA_DESEOS>();
            this.RESENAS = new HashSet<RESENAS>();
        }
    
        public int ID_USUARIO { get; set; }
        public string CORREO { get; set; }
        public string PASS { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CEDULA { get; set; }
        public Nullable<int> ID_GENERO { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<int> ID_DIR_PRI { get; set; }
        public Nullable<double> VAL_USU { get; set; }
        public System.DateTime FEC_CREA { get; set; }
        public int ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AFILIADOS> AFILIADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARRITO_COMPRAS> CARRITO_COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCIONES> DIRECCIONES { get; set; }
        public virtual DIRECCIONES DIRECCIONES1 { get; set; }
        public virtual GENERO GENERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_DESEOS> LISTA_DESEOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESENAS> RESENAS { get; set; }
    }
}
