//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppAdminDesktop_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.DETALLE_REGALO = new HashSet<DETALLE_REGALO>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public int ID_VENTA { get; set; }
        public System.DateTime FECHA_VENTA { get; set; }
        public double MONTO { get; set; }
        public double IVA { get; set; }
        public int DIAS_TARDA { get; set; }
        public double COSTO_ENVIO { get; set; }
        public int ID_ESTADO_ENVIO { get; set; }
        public int ID_DIRECCION { get; set; }
        public int ID_USURIO { get; set; }
        public int ID_ESTADO_VENTA { get; set; }
        public int ID_METODO_PAGO { get; set; }
        public double SATISFACION { get; set; }
        public string OBSERVACIONES { get; set; }
        public int COMO_REGALO { get; set; }
        public Nullable<int> ID_COD_DES { get; set; }
        public Nullable<int> ID_COD_AFILIADO { get; set; }
        public string CODIGO_RASTREO { get; set; }
        public int ESTADO { get; set; }
    
        public virtual AFILIADOS AFILIADOS { get; set; }
        public virtual COD_DESCUENTO COD_DESCUENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_REGALO> DETALLE_REGALO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual ESTADOS_ENVIOS ESTADOS_ENVIOS { get; set; }
        public virtual ESTADOS_VENTA ESTADOS_VENTA { get; set; }
        public virtual METODOS_PAGO METODOS_PAGO { get; set; }
    }
}
